//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumpStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GumpStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gump Studio.NET.
        /// </summary>
        public static string About_Gump_Studio_NET {
            get {
                return ResourceManager.GetString("About_Gump_Studio_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (C) Bradley Uffner, 2004.
        /// </summary>
        public static string C__Bradley_Uffner__2004 {
            get {
                return ResourceManager.GetString("C__Bradley_Uffner__2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cmdAdd_Image {
            get {
                object obj = ResourceManager.GetObject("cmdAdd_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cmdCache_Image {
            get {
                object obj = ResourceManager.GetObject("cmdCache_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cmdMoveDown_Image {
            get {
                object obj = ResourceManager.GetObject("cmdMoveDown_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cmdMoveUp_Image {
            get {
                object obj = ResourceManager.GetObject("cmdMoveUp_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cmdRemove_Image {
            get {
                object obj = ResourceManager.GetObject("cmdRemove_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Version: .
        /// </summary>
        public static string Core_Version__ {
            get {
                return ResourceManager.GetString("Core_Version__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating cache file:
        ///.
        /// </summary>
        public static string Error_creating_cache {
            get {
                return ResourceManager.GetString("Error_creating_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error drawing itemID: {0} it has been replaced with the \&quot;no draw\&quot; item..
        /// </summary>
        public static string Error_drawing_itemID___ {
            get {
                return ResourceManager.GetString("Error drawing itemID...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed update check..
        /// </summary>
        public static string Failed_update_check_ {
            get {
                return ResourceManager.GetString("Failed_update_check_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Error.
        /// </summary>
        public static string Font_Error {
            get {
                return ResourceManager.GetString("Font Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait, Generating Static Art Cache...  
        ///.
        /// </summary>
        public static string Generating_static_art_cache {
            get {
                return ResourceManager.GetString("Generating_static_art_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gump Studio was written by Bradley Uffner in January of 2003..
        /// </summary>
        public static string Gump_Studio_was_written___ {
            get {
                return ResourceManager.GetString("Gump_Studio_was_written___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GumpID.
        /// </summary>
        public static string Invalid_GumpID {
            get {
                return ResourceManager.GetString("Invalid GumpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name__ {
            get {
                return ResourceManager.GetString("Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PictureBox1_Image {
            get {
                object obj = ResourceManager.GetObject("PictureBox1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding the cache may take several minutes debending on the speed of your computer.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string Rebuild_longtime {
            get {
                return ResourceManager.GetString("Rebuild_longtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Size.
        /// </summary>
        public static string Reset_Size {
            get {
                return ResourceManager.GetString("Reset Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: .
        /// </summary>
        public static string Size__ {
            get {
                return ResourceManager.GetString("Size__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
